name: hello world

on:                           # OR simple, "on: [push]" 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:          # for manual workflow start

jobs:
  my-build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Echo a string
        run: echo "Hello, world"

      - name: Multiline script
        run: |
          node -v
          npm -v
